server {
  listen 80;
  server_name portal.example.com;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl http2;
  server_name gestorapp.labsec.tech;
  ssl_certificate     /etc/nginx/certs/origin.crt;
  ssl_certificate_key /etc/nginx/certs/origin.key;
  #ssl_certificate /etc/nginx/certs/fullchain.pem;
  #ssl_certificate_key /etc/nginx/certs/privkey.pem;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers off;
  ssl_session_timeout 1d;
  ssl_session_cache shared:SSL:10m;

  add_header X-Frame-Options DENY always;
  add_header X-Content-Type-Options nosniff always;
  add_header Referrer-Policy no-referrer always;
  add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;
  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

  proxy_http_version 1.1;
  proxy_set_header Host $host;
  proxy_set_header X-Forwarded-Host $host;
  proxy_set_header X-Forwarded-Proto https;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header Connection "";
  proxy_read_timeout 120s;

  location /api/auth/saml/login {
    limit_req zone=auth_limit burst=20 nodelay;
    proxy_pass http://api_upstream/api/auth/saml/login;
  }

  location /api/auth/saml/acs {
    limit_req zone=auth_limit burst=20 nodelay;
    proxy_pass http://api_upstream/api/auth/saml/acs;
  }

  location /api/webhooks/ {
    limit_req zone=webhook_limit burst=250 nodelay;
    proxy_pass http://api_upstream/api/webhooks/;
  }

  location /api/ {
    limit_req zone=api_limit burst=80 nodelay;
    proxy_pass http://api_upstream/api/;
  }

  location / {
    proxy_pass http://web_upstream;
  }

  # Opcional: habilite apenas se voce configurar Authenticated Origin Pulls no Cloudflare.
  # ssl_client_certificate /etc/nginx/certs/cloudflare-origin-pull-ca.pem;
  # ssl_verify_client optional;
}
